### ISSUE TITLE
Espressif PIO 6.x build is broken in release 1.7

### ISSUE THREAD

**Issue by lyusupov** [erstec/APRS-ESP#35]
### Build error messages

```
lib/LibAPRS_ESP32/AFSK.cpp: In function 'void AFSK_Poll(bool, bool, uint8_t)':
lib/LibAPRS_ESP32/AFSK.cpp:908:11: error: 'i2s_write_bytes' was not declared in this scope
       if (i2s_write_bytes(I2S_NUM_0, (char *)&pcm_out, (x * sizeof(uint16_t)), portMAX_DELAY) == ESP_OK)
           ^~~~~~~~~~~~~~~
lib/LibAPRS_ESP32/AFSK.cpp:908:11: note: suggested alternative: 'i2s_write_expand'
       if (i2s_write_bytes(I2S_NUM_0, (char *)&pcm_out, (x * sizeof(uint16_t)), portMAX_DELAY) == ESP_OK)
           ^~~~~~~~~~~~~~~
           i2s_write_expand
lib/LibAPRS_ESP32/AFSK.cpp:945:9: error: 'i2s_write_bytes' was not declared in this scope
         i2s_write_bytes(I2S_NUM_0, (char *)&pcm_out, (ADC_SAMPLES_COUNT * sizeof(uint16_t)), portMAX_DELAY);
         ^~~~~~~~~~~~~~~
lib/LibAPRS_ESP32/AFSK.cpp:945:9: note: suggested alternative: 'i2s_write_expand'
         i2s_write_bytes(I2S_NUM_0, (char *)&pcm_out, (ADC_SAMPLES_COUNT * sizeof(uint16_t)), portMAX_DELAY);
         ^~~~~~~~~~~~~~~
         i2s_write_expand
*** [.pio/build/esp32dev-sa818/lib93b/LibAPRS_ESP32/AFSK.cpp.o] Error 1

```

### To reproduce:

1) edit platformio.ini as follows:

```
;platform = espressif32@3.5.0
platform = espressif32@6.0.1
```

2) execute `pio run`

**Comment by erstec** [comment]
@lyusupov I have no plans to swith to 6.0.1 atm.
On 3.5.0 it builds and works as should be for >3 weeks on my table without issues
If you see fix for 6.0.1 - you are welcome to contribute

**Comment by lyusupov** [comment]
the fix was introduced in https://github.com/erstec/APRS-ESP/commit/caa21cfa1ef960f7ea8063352ff1a2bb2f42e0b2

i2s_write() it is known to work nicely as a replacement for i2s_write_bytes() - this method is in use by https://github.com/earlephilhower/ESP8266Audio library :
see this https://github.com/earlephilhower/ESP8266Audio/issues/401 and that https://github.com/earlephilhower/ESP8266Audio/blob/master/src/AudioOutputI2S.cpp#L343 for details.

**Comment by erstec** [comment]
> the fix was introduced in [caa21cf](https://github.com/erstec/APRS-ESP/commit/caa21cfa1ef960f7ea8063352ff1a2bb2f42e0b2)
> 
> i2s_write() it is known to work nicely as a replacement for i2s_write_bytes() - this method is in use by https://github.com/earlephilhower/ESP8266Audio library : see this [earlephilhower/ESP8266Audio#401](https://github.com/earlephilhower/ESP8266Audio/issues/401) and that https://github.com/earlephilhower/ESP8266Audio/blob/master/src/AudioOutputI2S.cpp#L343 for details.

Thank you, I will look at that, perform at least week tests and then relase.

**Comment by erstec** [comment]
Currently it is merged to master branch and ready to be tested.
New targets for ESP32-S3 are introduced and build systeme are sane.
If tests on "non S3" MCU using 6.0.1 Platform manager will success - I will propose MR with update.
